- name: raspberry_pi-arm64-bookworm
  type: raspberry
  img_download_url: "https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2025-10-02/2025-10-01-raspios-bookworm-arm64-lite.img.xz.torrent"
  img_hash_url: "https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2025-10-02/2025-10-01-raspios-bookworm-arm64-lite.img.xz.sha256"
  env:
    ARCH: arm64
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 56-klipperscreen
  rpi_json:
    name: "MainsailOS (Crafter3D) $VERSION$ - Raspberry Pi (64-bit)"
    description: "Raspberry Pi OS with Klipper/Moonraker/Mainsail, built by Crafter3D"
    icon: "https://crafter3d.github.io/MainsailOS/rpi-imager.png"
    init_format: "systemd"
    devices:
      - "pi3-64bit"
      - "pi4-64bit"
      - "pi5-64bit"
