#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# Use HOSTNAME variable when set, falling back to lowercase DIST_NAME
NEW_HOSTNAME=${HOSTNAME:-${DIST_NAME,,}}

function get_parent {
    grep VERSION_CODENAME /etc/os-release | cut -d '=' -f2
}

########################################
# Create <DIST_NAME>-release file      #
########################################

echo "Create ${DIST_NAME} release file"
echo "${DIST_NAME} release ${RELEASE_TAG} ($(get_parent))" > /etc/"${DIST_NAME,,}"-release

########################################
# Workaround for Armbian based OS      #
########################################

### NOTE: The 'distro' Python package used by Moonraker picks the first file after sorting.
###       This hack is necessary because Armbian relies on upgrades to the original release file.
###       To work around this, we symlink mainsailos-release to aaaa-release, which Moonraker reads.
if [[ -f "/etc/armbian-release" || -f "/etc/orangepi-release" ]]; then
    echo "Applying release file workaround"
    ln -sf /etc/"${DIST_NAME,,}"-release /etc/aaaa-release
fi

########################################
# Set Hostname to DIST_NAME            #
########################################

if [ -f /etc/hostname ]; then
    read -r ORG_HOSTNAME < /etc/hostname
    ORG_HOSTNAME=${ORG_HOSTNAME//$'\n'/}
else
    ORG_HOSTNAME=raspberrypi
fi

echo "$NEW_HOSTNAME" > /etc/hostname
sed -i -e "s@${ORG_HOSTNAME}@$NEW_HOSTNAME@g" /etc/hosts

########################################
# Install dependencies for other       #
# Projects                             #
########################################

echo "Install dependencies for other projects"
DEPS=( \
    # python3-serial is needed later on for possible CAN adapters
    python3-serial \
    # python3-opencv is needed for moonraker-obico by obico in version 2.0
    python3-opencv \
)
apt-get install -y "${DEPS[@]}"

########################################
# Set default password for BASE_USER   #
########################################

echo "Setting default password for ${BASE_USER}"
echo "${BASE_USER}:crafter3d" | chpasswd

########################################
# Set default locale (en_US.UTF-8)     #
########################################

echo "Setting default locale to en_US.UTF-8"
sed -i 's/^# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8

########################################
# Disable Raspberry Pi OS userconf     #
# service to prevent login blocking on #
# raw-flash boots (user already exists)#
########################################

if [[ -f /etc/systemd/system/multi-user.target.wants/userconfig.service ]] || \
   systemctl list-unit-files userconfig.service &>/dev/null; then
    echo "Disabling userconfig.service (user already provisioned)"
    systemctl_if_exists disable userconfig.service
fi
if systemctl list-unit-files cancel-rename.service &>/dev/null; then
    echo "Disabling cancel-rename.service"
    systemctl_if_exists disable cancel-rename.service
fi
