#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Install first-boot script & service #
########################################

install -d -m 0755 /opt/crafter3d
cp /files/postrename /opt/crafter3d/firstboot.sh
chmod 0755 /opt/crafter3d/firstboot.sh

cp /files/crafter3d-firstboot.service /etc/systemd/system/crafter3d-firstboot.service
systemctl_if_exists enable crafter3d-firstboot.service
